# Generated by Django 4.0.4 on 2022-05-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('country', models.CharField(max_length=45)),
                ('country_num', models.CharField(max_length=45)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'context',
                'managed': False,
            },
        ),
    ]
