# Generated by Django 4.0.4 on 2022-06-10 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'managed': False},
        ),
    ]
